<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO2pVyBL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO2pVyBL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO2pVyBL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO2pVyBL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerO2pVyBL\App_KernelDevDebugContainer([
    'container.build_hash' => 'O2pVyBL',
    'container.build_id' => 'dea1d202',
    'container.build_time' => 1738166432,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO2pVyBL');
